# 单节点es

---
# PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: n9e
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi

---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: n9e
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels: 
        app: elasticsearch
    spec:
      # nodeSelector:
      #   eks.amazonaws.com/nodegroup: node-8c-32G
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: elasticsearch:7.17.9
        ports:
        - name: rest
          containerPort: 9200
        resources:
          limits:
            cpu: 1000m
            memory: 2G
          requests:
            cpu: 1000m
            memory: 1G
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms1024m -Xmx1024m"
        - name: network.host
          value: "0.0.0.0"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch

---
# Service
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: n9e
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest

