# https://juejin.cn/post/6967934876045557790
# https://www.jaegertracing.io/docs/1.43/deployment/#all-in-one
# https://jckling.github.io/2021/05/10/Jaeger/Jaeger%20+%20Elasticsearch%20+%20Kibana/
# 下面这个是all-in-one的

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: n9e
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.43
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP      
        - containerPort: 16686
          protocol: TCP  
        - containerPort: 14268
          protocol: TCP  
        - containerPort: 9411
          protocol: TCP                                    

---
# Service 
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: n9e
spec:
  ports:
    - port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
  clusterIP: None

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: n9e
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - jaeger.xxx.com
    secretName: xxx-com-tls-secret
  rules:
  - host: jaeger.xxx.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger
            port:
              number: 16686
